services:
  app:
    image: github.com/bkhablenko/kotlin-spring-boot-template:${CIRCLE_SHA1:-latest}
    platform: linux/amd64
    build:
      context: .
    environment:
      DB_HOST: postgres
      LOGGING_STRUCTURED_FORMAT_CONSOLE: ecs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.1-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: kotlin-spring-boot-template
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d kotlin-spring-boot-template"]
      interval: 10s
      timeout: 3s
      retries: 5

  # https://github.com/Redocly/redoc
  redoc:
    image: redocly/redoc:v2.1.1
    environment:
      SPEC_URL: openapi.yaml
      REDOC_OPTIONS: >-
        expand-responses="200"
        json-sample-expand-level="3"
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    ports:
      - "8090:80"
