version: 2.1

orbs:
  gradle: circleci/gradle@4.1.0

jobs:
  build:
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    machine:
      image: ubuntu-2404:2025.09.1
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew clean build
      - store_test_results:
          path: build/test-results/test
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - docker-compose.yml
            - docker-entrypoint.sh
            - Dockerfile
  docker:
    docker:
      - image: cimg/base:2026.03
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker compose build app --no-cache

workflows:
  main:
    jobs:
      - build
      - docker:
          requires:
            - build